name: Get commit metadata
on:
  workflow_call:
    outputs:
      sha_short:
        description: Short (7-character) SHA hash
        value: ${{ jobs.get-commit-metadata.outputs.sha_short }}
      timestamp:
        description: Unix timestamp of the commit
        value: ${{ jobs.get-commit-metadata.outputs.timestamp }}

jobs:
  get-commit-metadata:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.commit.outputs.sha_short }}
      timestamp: ${{ steps.commit.outputs.timestamp }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(git log -1 --format="%at")" >> "$GITHUB_OUTPUT"
