name: "Update devenv and flake lockfile"

on:
  workflow_call:
    inputs:
      cache-size:
        required: false
        type: string
        default: 3G
  schedule:
    - cron: "0 17 * * *" # Runs daily at 01:00 SGT

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: ${{ inputs.cache-size }}

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Update flake lockfile
        run: devenv update

      - name: Test
        run: devenv test

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update devenv and flake lockfile"
