name: Run devenv test
on:
  push:
  workflow_call:
    inputs:
      cache-size:
        required: false
        type: string
        default: 3G

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: ${{ inputs.cache-size }}

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test
        run: devenv test
